name: Deploy feature environment

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'

concurrency:
  group: deploy-feature-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          echo "github.ref:       ${{ github.ref }}"
          echo "github.ref_name:  ${{ github.ref_name }}"
          echo "github.event.ref: ${{ github.event.ref }}"
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          config: config-aws-develop.json
          environment: ${{ inputs.branch }}